FROM nfd-traceroute

# Install necessary build tools
RUN apt-get update && apt-get install -y \
    cmake build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy and build the producer application
COPY producer /producer
RUN mkdir /producer/build && cd /producer/build && cmake .. && make

# Set the entrypoint to start NFD and run the producer
ENTRYPOINT ["/start-nfd.sh"]
CMD ["/producer/build/simple-producer", "p2", "/producer/prefix"]

