services:
  client:
    image: traceroute-client
    container_name: client
    networks:
      ndn-net:
    volumes:
      - ./configs/nfd1.conf:/etc/ndn/nfd.conf:ro
      - ./scripts/start-nfd.sh:/start-nfd.sh:ro
    command: >
      sh -c "/start-nfd.sh;
             sleep 5;
             nfdc face create tcp://intermediate;
             nfdc route add /producer/prefix tcp://intermediate;
             /client/build/traceroute-client /producer/prefix"

  producer:
    image: simple-producer
    container_name: producer
    networks:
      ndn-net:
    volumes:
      - ./configs/nfd2.conf:/etc/ndn/nfd.conf:ro
      - ./scripts/start-nfd.sh:/start-nfd.sh:ro
    command: >
      sh -c "/start-nfd.sh;
             sleep 5;
             nfdc face create tcp://intermediate;
             /producer/build/simple-producer p2 /producer/prefix"

  intermediate:
    image: nfd-traceroute
    container_name: intermediate
    networks:
      ndn-net:
    volumes:
      - ./configs/intermediate.conf:/etc/ndn/nfd.conf:ro
      - ./scripts/start-nfd.sh:/start-nfd.sh:ro
    command: >
      sh -c "/start-nfd.sh;
             sleep 5;
             nfdc face create tcp://client;
             nfdc face create tcp://producer;
             nfdc route add /producer/prefix tcp://producer;
             nfdc route add /ndn/forwarder1 tcp://client;
             tail -f /dev/null"

networks:
  ndn-net:

